### ISSUE TITLE
Results on BiT-S

### ISSUE THREAD

**Issue by BierOne** [YongHyun-Ahn/LINe-Out-of-Distribution-Detection-by-Leveraging-Important-Neurons#2]
Hi, there!

I sincerely appreciate this outstanding work. I find that the BiT-S-R101x1 model is mentioned in your README file. Have you ever implemented your LINE on this model? If so, would you mind releasing your results on this BiT-S-R101x1? Thank you so much.

**Comment by YongHyun-Ahn** [comment]
Hi @BierOne, 

Thank you for your comment. 
We didn't implement LINe on the BiT model. Since this repository is the initial version and still updating, some of the details in the files are unused or changed. BiT-S-R101x1 is one of them.
Thanks for letting us know. We will update README soon. 

Thank you.

**Comment by BierOne** [comment]
got it :)
